[project]
name = "ch05"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain-core>=0.3.34",
    "langchain-openai>=0.3.4",
]
