[project]
name = "ch09"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain>=0.3.20",
    "langchain-openai>=0.3.8",
    "langgraph>=0.3.7",
]

[dependency-groups]
dev = [
    "ruff>=0.11.0",
]
